theme: jekyll-theme-midnight
github:
  home: https://littleunixcorn.github.io/Unicorns
  research: https://littleunixcorn.github.io/Unicorns/CONTENT/RESEARCH
  resources: https://littleunixcorn.github.io/Unicorns/CONTENT/RESOURCES
  tweaks: https://littleunixcorn.github.io/Unicorns/CONTENT/TWEAKS
